name: Lighthouse Check

on: [pull_request]

jobs:
  lhci:
    name: Run Lighthouse CI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: "14"

      - name: Wait for the Netlify Web Preview
        uses: jakepartusch/wait-for-netlify-action@v1
        id: netlify
        with:
          site_name: "gmadugm"
          max_timeout: 120

      - name: Running Lighthouse CI
        id: lhci
        shell: bash
        run: |
          npm i -g @lhci/cli@0.8.x
          echo -e "\n"
          echo "Start collecting LH report..."
          lhci collect --url=${{ steps.netlify.outputs.url }} --url=${{ steps.netlify.outputs.url }}/jnc --url=${{ steps.netlify.outputs.url }}/nao --url=${{ steps.netlify.outputs.url }}/a-talk
          echo -e "\n"
          echo "Start uploading the report..."
          lhci upload --target "temporary-public-storage" --githubAppToken "$LHCI_GITHUB_APP_TOKEN" --githubToken "$GITHUB_TOKEN"
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}